"""줄바꿈 기회가 없는 제목·버전·경로와 다운로드 상태를 함께 재현한다."""
long='긴문자열 日本語 English 😀 '+ 'W'*400
settings=dict(app_name='Phrolova',download_dir='/recordings/'+long,live_download_dir='/recordings/live',vod_download_dir='/recordings/vod',ffmpeg_path='ffmpeg',streamlink_version='7.0',monitor_interval=30,host=long,port=8000,ffmpeg_version='7.0',authenticated=True,discord_bot_configured=True,keep_download_parts=True,max_record_retries=3,chzzk_time_machine_enabled=False,chzzk_stream_mode='standard',chzzk_time_machine_shift=0,chzzk_time_machine_offset=0,save_live_preview=False,live_filename_template='{name} {title}',vod_filename_template='{name} {title}',live_download_condition='all',watchalong_tags='같이보기',live_format='ts',vod_format='mp4',recording_quality='best',vod_max_concurrent=2,vod_default_quality='best',vod_max_speed=0,chat_archive_enabled=True,discord_webhook_configured=True,discord_notify_events=['all'],discord_mention_events=[],discord_mention_target='@here',discord_notify_ttl=3600,notification_kinds=[dict(value='recording_started',label='녹화 시작',description=long)],split_download_dirs=False,vod_chzzk_dir='/vod',vod_external_dir='/external')
tasks=[dict(task_id=str(i),url='https://youtube.com/watch?v=abcdefghijk',title=long,state=s,progress=37,quality='best',output_path='/output/'+long,error_message=long if s=='error' else '',created_at='2026-10-07T12:00:00Z',started_at=None,completed_at='2026-10-07T12:00:00Z' if s=='completed' else None,download_speed=12.34,downloaded_bytes=1024,total_bytes=4096,eta_seconds=320) for i,s in enumerate(['idle','downloading','paused','cancelling','completed','error'])]
channels=[dict(channel_id=str(i),platform='chzzk',channel_name=long,title=long,category=long,is_live=i!=0,auto_record=True,tags=[long,'tag'],last_error=long if i==2 else '',recording=dict(is_recording=i==1,state='recording',duration_seconds=3600,output_path='/output/'+long,start_time=None,file_size_bytes=4096,download_speed=12.34,bitrate=10000)) for i in range(3)]
stats=dict(live=dict(total_duration_seconds=3600,total_size_bytes=4096,total_sessions=1,active_recordings=1,by_channel=[dict(channel_id='1',channel_name=long,session_count=1,total_duration_seconds=3600,total_size_bytes=4096,live_detected_count=10)]),vod=dict(total_completed=1,total_size_bytes=4096,by_type=dict(chzzk=1,external=0)),storage=dict(download_dir='/output/'+long,used_bytes=4096,total_bytes=8192,free_bytes=4096),recent_sessions=[dict(channel_id='1',channel_name=long,ended_at='2026-10-07T12:00:00Z',duration_seconds=3600,file_size_bytes=4096)])
fixtures={'settings':settings,'tasks':tasks,'channels':channels,'stats':stats,'long':long}
FIX = fixtures

FIX['imports'] = [dict(id=str(i), url='https://youtube.com/@'+long, state=state, added_count=50, skipped_count=10, error=long if state=='error' else None) for i,state in enumerate(['queued','collecting','error'])]
FIX['channels'][2].update(auto_record_eligible=False,download_condition='watchalong',download_hold_reason='condition_mismatch',broadcast_tags=[long])
