import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "ko" | "en" | "ja";

export const LANGUAGE_OPTIONS: { value: Language; label: string }[] = [
    { value: "ko", label: "한국어" },
    { value: "en", label: "English" },
    { value: "ja", label: "日本語" },
];

const messages: Record<Exclude<Language, "ko">, Record<string, string>> = {
    en: {
        "시작 시 저장된 CDN 설정 적용": "Use saved CDN setting when starting",
        "영상 정보를 가져오지 못했습니다. 해당 항목에서 다시 조회해 주세요.": "Could not fetch video information. Retry this item.",
        "CHZZK VOD 준비 목록": "CHZZK VOD preparation",
        "CHZZK 다시보기 URL을 여기에 놓으세요.": "Drop CHZZK VOD URLs here.",
        "링크를 놓거나 여러 URL을 줄바꿈으로 입력하세요. 등록 후 화질을 선택할 수 있습니다.": "Drop links or enter one URL per line. Choose quality after registration.",
        "CHZZK 다시보기 URL 목록": "CHZZK VOD URL list",
        "VOD 등록": "Register VODs",
        "전체 다운로드 시작": "Start all downloads",
        "지원하지 않는 주소": "Unsupported URL",
        "CHZZK 다시보기 주소를 입력해 주세요.": "Enter a CHZZK VOD URL.",
        "한 번에 최대 100개의 URL을 등록할 수 있습니다.": "Register up to 100 URLs at once.",
        "이미 등록된 VOD입니다.": "This VOD is already registered.",
        "동시 다운로드 제한은 서버 설정을 따릅니다.": "Concurrent downloads follow server settings.",
        "정보 조회 중": "Fetching metadata",
        "정보 조회 실패": "Metadata failed",
        "다운로드 준비 완료": "Ready to download",
        "병합 중": "Merging",
        "검증 중": "Verifying",
        "취소됨": "Cancelled",
        "영상별 화질 선택": "Video quality",
        "기본 화질이 제공되지 않아 사용 가능한 화질을 선택했습니다.": "Default quality is unavailable; an available quality was selected.",
        "정보 다시 조회": "Retry metadata",
        "완료 목록 정리": "Clear completed history",
        "완료된 작업 이력만 정리합니다. 저장된 영상 파일은 삭제하지 않습니다.": "Clear completed history only. Saved video files are kept.",
        "영상 파일은 삭제하지 않습니다.": "Video files are kept.",
        "이력 제거": "Remove history",
        "작업 이력을 제거했습니다.": "Task history removed.",
        "정보 조회를 시작했습니다.": "Metadata lookup started.",
        "화질을 변경했습니다.": "Quality updated.",
        "다운로드를 시작했습니다.": "Download started.",
        "녹화 시작하기": "Start recording", "상세 보기": "Details", "상세 접기": "Collapse details", "태그": "Tags", "녹화 중지": "Stop recording",
        "시청자": "Viewers",
        "채널 관리": "Manage channel",
        "위로 이동": "Move up", "아래로 이동": "Move down", "명령 복사": "Copy command", "메시지 갱신에 실패했습니다. 이전 내용을 표시합니다.": "Could not refresh messages. Showing previous content.",
        "다른 채널": "Other channels",
        "채팅 기록을 불러오는 중": "Loading chat history",
        "다운로드 목록을 불러오는 중": "Loading downloads",
        "로그 목록을 불러오는 중": "Loading log files",
        "통계를 불러오는 중": "Loading statistics",
        "다운로드한 다시보기, 클립 및 영상이 저장됩니다.": "Downloaded VODs, clips, and videos are saved here.",
        "등록한 채널의 방송 상태와 녹화를 관리합니다.": "Monitor your channels and manage live recordings.",
        "등록된 채널이 없습니다.": "No channels added yet.",
        "채널을 추가하면 방송 상태를 확인하고 자동으로 녹화할 수 있습니다.": "Add a channel to monitor its live status and record automatically.",
        "채널 상세 보기": "Channel details",
        "녹화 정보": "Recording details",
        "다시보기, 클립 및 지원되는 영상을 다운로드합니다.": "Download VODs, clips, and other supported videos.",
        "다운로드 상태 필터": "Download status filters",
        "해당 상태의 다운로드가 없습니다.": "No downloads with this status.",
        "다른 상태를 선택해 작업을 확인하세요.": "Select another status to view your downloads.",
        "다운로드를 완료하지 못했습니다. 다시 시도하거나 영상 주소와 인증 설정을 확인하세요.": "The download failed. Try again or check the video URL and authentication settings.",
        "다운로드 목록을 불러오지 못했습니다. 잠시 후 다시 시도하세요.": "Unable to load downloads. Try again shortly.",
        "다운로드 진행률": "Download progress",
        "녹화, 다운로드, 인증, 알림 및 애플리케이션 동작을 구성합니다.": "Configure recording, downloads, authentication, notifications, and app behavior.",
        "라이브 녹화 설정": "Live recording settings",
        "Chzzk 녹화 방식": "Chzzk recording mode",
        "서버 주소": "Server address",
        "화면을 표시하지 못했습니다.": "Unable to display this page.",
        "페이지를 새로고침하거나 라이브 화면으로 돌아가세요.": "Refresh the page or return to Live.",
        "라이브로 이동": "Go to Live",
        "페이지 이동": "Navigate to a page",
        "페이지 검색...": "Search pages...",
        "채팅 내용 검색": "Search chat messages",
        "닉네임 검색": "Search nicknames",
        "같이보기만 녹화": "Record watch-along streams only",
        "같이보기 제외하고 녹화": "Record streams except watch-alongs",
        "서버 연결이 끊겼습니다. 다시 연결하는 중입니다.": "Server connection lost. Reconnecting.",

        "라이브 녹화·영상 다운로드": "Live recording · video downloads",
        "시작 전에": "Before you start",
        "실시간": "Live",
        "오류 세부 정보": "Error details",
        "대기 중·완료·실패한 작업만 목록에서 삭제합니다. 진행 중이거나 일시정지한 작업과 저장된 파일은 유지됩니다.": "Only queued, completed, and failed tasks are removed. Active or paused tasks and saved files remain.",

        "다시보기·클립 링크": "Chzzk VOD or clip link",
        "@핸들 또는 동영상 ID": "@handle or video ID",
        "영상 링크 입력": "Video link",
        "Chzzk 다시보기와 클립, YouTube와 외부 영상을 추가하고 다운로드 상태를 관리합니다.": "Add Chzzk VODs and clips, YouTube videos, or other supported links, then track downloads.",

        "같이보기 방송은 자동 녹화하지 않도록 설정되어 있습니다.": "Watch-along streams are excluded from automatic recording.",
        "같이보기 방송만 녹화하도록 설정되어 있어 이 방송은 저장하지 않습니다.": "Only watch-along streams are recorded, so this stream will not be saved.",
        "방송의 같이보기 태그가 설정한 태그와 일치하지 않습니다.": "The stream’s watch-along tag does not match the selected tags.",
        "방송 태그가 설정한 녹화 조건과 일치하지 않습니다.": "The stream tags do not match the recording condition.",
        "Chzzk 다시보기와 클립, YouTube 및 외부 영상을 추가하고 다운로드 상태를 관리합니다.": "Add Chzzk VODs and clips, YouTube videos, or other supported links, then track their downloads.",
        "아직 추가한 영상이 없습니다": "No videos added yet",
        "영상 주소를 추가하면 다운로드 진행 상황과 저장 위치를 확인할 수 있습니다.": "Add a video link to track its download and find the saved file.",

        "채널 녹화 설정": "Channel recording settings",
        "라이브 채널 추가": "Add live channel",
        "현재 방송 태그": "Current stream tags",
        "Chzzk 같이보기 방송": "Chzzk watch-along stream",
        "Chzzk의 같이보기 정보와 방송 태그를 확인합니다. 변경 사항은 다음 자동 녹화부터 적용되며, 진행 중인 녹화와 수동 녹화에는 영향을 주지 않습니다.": "Uses Chzzk watch-along details and stream tags. Changes apply to the next automatic recording and do not affect ongoing or manual recordings.",
        "설정한 녹화 조건에 맞지 않는 방송입니다.": "This stream does not match the recording condition.",
        "자동 녹화 보류": "Auto-record on hold",
        "녹화 설정": "Recording settings",
        "채팅 기록": "Chat history",
        "진행 상황과 저장한 파일은 영상 다운로드 화면에서 확인할 수 있습니다.": "Check progress and saved files on the Video Downloads page.",
        "다운로드를 완료하지 못했습니다. 오류 세부 정보": "Download could not be completed. Error details",
        "화질": "Resolution",
        "다운로드 속도 제한 (MB/s)": "Download speed limit (MB/s)",
        "0으로 설정하면 속도 제한 없이 다운로드합니다.": "Set to 0 for unlimited speed.",
        "대기 중·완료·실패한 항목을 목록에서 삭제할까요? 진행 중이거나 일시정지한 항목은 유지됩니다.": "Remove queued, completed, and failed items? Active and paused downloads will remain.",
        "다운로드 목록에서 {count}개 항목을 삭제했습니다.": "Removed {count} items from the download list.",
        "목록 정리에 실패했습니다.": "Could not clear the download list.",
        "작업 순서 변경에 실패했습니다.": "Could not change the task order.",
     "실패": "Failed", "다운로드 관리": "Download manager", "방송 상태를 확인하고 채널별 자동 녹화와 녹화 조건을 관리합니다.": "Monitor live status and manage automatic recording and recording conditions by channel.", "이 채널의 녹화 조건에 맞지 않는 방송입니다.": "This stream does not match the channel's recording condition.", "같이보기 정보를 확인하고 있습니다.": "Checking watch-along details.", "자동 녹화 대기": "Auto-record waiting", "자동 녹화 꺼짐": "Auto-record off",
        "모든 방송 녹화": "Record all live streams", "같이보기 방송만 녹화": "Record watch-along streams only", "같이보기 방송 제외": "Exclude watch-along streams",
        "기본 녹화 조건": "Default recording condition", "기본 녹화 조건을 저장했습니다.": "Default recording condition saved.", "녹화 조건을 저장하지 못했습니다.": "Could not save the recording condition.", "녹화 조건을 불러오지 못했습니다.": "Could not load the recording condition.",
        "같이보기 태그": "Watch-along tags", "‘같이보기’는 전체 같이보기를 선택합니다. 특정 콘텐츠 태그는 쉼표로 구분하세요.": "Use ‘watch-along’ to match all watch-along streams. Separate specific content tags with commas.", "예: 같이보기": "e.g. watch-along", "Chzzk의 같이보기 정보와 방송 태그를 기준으로 판단합니다. 채널별 설정이 기본값보다 우선합니다.": "Uses Chzzk watch-along details and stream tags. Channel settings take precedence over the default.", "기본 조건 저장": "Save default condition", "현재 기본값": "Current default", "방송이 시작되고 녹화 조건에 맞으면 자동으로 저장합니다.": "Automatically record when a stream starts and matches the recording condition.", "녹화 조건": "Recording condition", "이 채널에만 적용합니다.": "Applies to this channel only.", "기본 조건 사용": "Use default condition",
        "채널 영상 목록 불러오기를 시작했습니다.": "Started loading videos from the channel.", "채널 영상 목록 불러오기 대기 중": "Waiting to load channel videos", "채널 영상 목록을 불러오는 중": "Loading channel videos", "채널 영상 목록 불러오기 완료": "Channel video list loaded", "채널 영상 목록 불러오기 중지됨": "Stopped loading channel videos", "채널 영상 목록을 불러오지 못했습니다.": "Could not load channel videos.", "목록 불러오기를 중지해도 이미 추가된 영상은 유지됩니다.": "Videos already added will remain if you stop loading the list.", "불러오기 중지": "Stop loading",
        "라이브 저장 위치": "Live recording location", "영상 저장 위치": "Video download location", "라이브 확인 주기 (초)": "Live status check interval (seconds)", "등록한 채널의 방송 상태를 확인하는 간격입니다 (5~300초).": "How often to check the live status of added channels (5–300 seconds).", "라이브 녹화 파일 형식": "Live recording file format", "TS와 MKV는 녹화가 중단되어도 재생할 수 있습니다. MP4는 중단 시 파일이 손상될 수 있습니다.": "TS and MKV files remain playable if recording stops. MP4 files may be damaged if recording is interrupted.", "기본 화질": "Default resolution", "영상 다운로드에 사용할 기본 해상도입니다.": "Default resolution for video downloads.", "라이브 녹화 화질": "Live recording resolution", "녹화할 해상도를 선택합니다. 높은 해상도일수록 저장 공간을 더 사용합니다.": "Choose a recording resolution. Higher resolutions use more storage.", "녹화 자동 재시도 횟수": "Recording retry attempts", "연결이 끊기거나 녹화에 실패했을 때 다시 시도할 횟수입니다.": "How many times to retry if the connection drops or recording fails.", "MP4는 대부분의 기기와 플레이어에서 재생할 수 있습니다.": "MP4 works with most devices and media players.",
        "다운로드를 취소할까요?": "Cancel this download?", "‘{title}’ 다운로드를 취소합니다.": "Cancel the download ‘{title}’?", "다운로드 취소": "Cancel download", "다운로드 취소를 요청했습니다.": "Download cancellation requested.", "다운로드를 취소하지 못했습니다.": "Could not cancel the download.", "다운로드를 다시 시작할까요?": "Retry this download?", "‘{title}’을(를) 다시 다운로드합니다.": "Download ‘{title}’ again?", "다운로드를 다시 시작했습니다.": "Download restarted.", "다운로드를 다시 시작하지 못했습니다.": "Could not restart the download.", "다운로드를 일시정지했습니다.": "Download paused.", "다운로드를 일시정지하지 못했습니다.": "Could not pause the download.", "다운로드를 재개했습니다.": "Download resumed.", "다운로드를 재개하지 못했습니다.": "Could not resume the download.", "다운로드 목록": "Download queue", "남은 시간": "Remaining", "일시정지하기": "Pause", "재개": "Resume", "폴더 열기": "Open folder", "파일 위치 열기": "Open file location", "다운로드 중": "Downloading", "일시정지": "Paused", "완료": "Completed", "취소 중": "Cancelling",
        "더 보기": "Show more",
        "YouTube 쿠키를 등록했습니다.": "YouTube cookies saved.",
        "선택 사항 · 공개 영상은 쿠키 없이 다운로드합니다. 로그인·연령 제한·멤버십 확인이 필요한 경우에만 등록한 쿠키를 사용합니다.": "Optional. Public videos download without cookies. Uploaded cookies are used only when sign-in, age verification, or membership is required.",
        "YouTube 쿠키 내보내기 안내": "How to export YouTube cookies",
        "채널 영상 수집을 시작했습니다.": "Started collecting channel videos.",
        "채널 영상 수집 대기 중": "Waiting to collect channel videos",
        "채널 영상을 불러오는 중": "Collecting channel videos",
        "채널 영상 수집 완료": "Channel collection complete",
        "채널 영상 수집 중지됨": "Channel collection stopped",
        "채널 영상 수집 실패": "Could not collect channel videos",
        "추가한 영상": "Videos added",
        "이미 목록에 있는 영상": "Videos already in the queue",
        "찾은 영상부터 다운로드합니다. 수집을 중지해도 추가된 영상은 유지됩니다.": "Videos download as they are found. Stopping collection keeps videos already added.",
        "수집 중지": "Stop collection",
        "영상을 찾으면 이곳에 표시됩니다.": "Videos will appear here as they are found.",
        "요청에 실패했습니다.": "The request failed.",
        "모니터링": "Monitoring", "미디어 허브": "Media Hub", "워크스페이스": "Workspace",
        "라이브 대시보드": "Live Dashboard", "다시보기 대시보드": "Video Dashboard", "통계": "Statistics", "로그": "Logs", "설정": "Settings",
        "알림 센터": "Notifications", "최근 앱 이벤트": "Recent app events", "모두 지우기": "Clear all", "아직 알림 내역이 없습니다.": "No notifications yet.",
        "메뉴 열기": "Open menu", "메뉴 닫기": "Close menu", "빠른 이동": "Quick navigation", "다운로드": "Downloads", "주 메뉴": "Main menu", "본문으로 이동": "Skip to content",
        "프로그램 설정": "App settings", "녹화 방식과 인증, 알림, 화면 테마 및 시스템 동작을 구성합니다.": "Configure recording, authentication, notifications, appearance, and system behavior.",
        "7개 항목": "7 sections", "저장하지 않은 변경사항": "Unsaved changes", "업데이트 가능": "Update available", "설정 탭": "Settings tabs",
        "활성 녹화": "active recordings", "용량 확인 기준 경로": "Storage path",
        "일반": "General", "인증": "Authentication", "알림": "Notifications", "외관": "Appearance", "시스템": "System", "정보": "About",
        "외관 설정": "Appearance", "언어": "Language", "앱에서 사용할 언어를 선택합니다.": "Choose the language used in the app.",
        "Chzzk": "Chzzk", "만료/미설정": "Expired / not configured", "NID_AUT 쿠키 값 입력...": "Enter the NID_AUT cookie value…", "NID_SES 쿠키 값 입력...": "Enter the NID_SES cookie value…", "유효함": "Valid", "업로드됨": "Uploaded", "없음": "None", "확인 중...": "Checking…", "상태 확인": "Check status", "저장": "Save", "검증": "Validate", "개발자 페이지": "developer page", "에서 앱을 등록하고 발급받은 API v2 인증 정보를 입력하세요.": " to register an app, then enter the API v2 credentials you received.", "Client ID": "Client ID", "Client Secret": "Client Secret", "X Spaces 녹화 시 사용할 Netscape 형식 쿠키 파일을 업로드하세요.": "Upload a Netscape-format cookie file for recording X Spaces.", "파일 선택": "Choose file", "업로드 중...": "Uploading…", "삭제": "Delete", "쿠키 파일이 삭제되었습니다.": "Cookie file deleted.", "쿠키 파일 삭제에 실패했습니다.": "Could not delete the cookie file.", "X Spaces 인증 파일이 준비되었습니다.": "The X Spaces authentication file is ready.",
        "연결 상태": "Connection status", "알림이 실제로 나가고 있는지 여기서 확인합니다.": "Check whether notifications are being delivered.", "상태 새로고침": "Refresh status", "테스트 발송": "Send test", "Bot 토큰 + 채널 ID 또는 Webhook URL 중 하나는 설정해야 알림이 전송됩니다.": "Set either a Bot token and channel ID, or a Webhook URL, to send notifications.", "Discord 채널 설정에서 URL 하나만 복사하면 끝납니다. 알림만 받을 거라면 이것으로 충분합니다.": "Copy a single URL from your Discord channel settings. This is all you need to receive notifications.", "권장": "Recommended", "설정됨": "Configured", "미설정": "Not configured", "설정됨 — 변경하려면 입력": "Configured — enter a new value to change", "Discord 채널 설정 → 연동 → 웹후크에서 만듭니다. Bot을 만들지 않아도 모든 알림이 정상 동작합니다.": "Create this in Discord channel settings → Integrations → Webhooks. Notifications work without creating a Bot.", "디스코드에서 원격 제어까지 하려면": "For remote control through Discord", "Bot을 등록하면 /status, /start, /stop 같은 슬래시 커맨드로 녹화를 제어할 수 있습니다. 알림만 받을 거라면 설정하지 않아도 됩니다.": "Register a Bot to control recordings with slash commands such as /status, /start, and /stop. You can leave this unset if you only need notifications.", "비워두면 기존 토큰을 유지합니다. Discord Developer Portal에서 발급받으세요. 토큰 변경은 재시작 후 적용됩니다.": "Leave this blank to keep the current token. Get one from the Discord Developer Portal. Token changes take effect after restarting.", "알림 채널 ID": "Notification channel ID", "Discord에서 개발자 모드를 켠 뒤 채널 우클릭 → 'ID 복사'로 얻은 숫자입니다.": "Enable Developer Mode in Discord, then right-click the channel and choose Copy ID.", "명령어 허용 사용자 ID": "Allowed user IDs for commands", "쉼표로 구분합니다. 비워두면 사용자 제한 없이 채널 조건만 적용됩니다.": "Separate IDs with commas. Leave blank to restrict commands by channel only.", "명령어 허용 채널 ID": "Allowed channel ID for commands", "비워두면 위 알림 채널에서만 명령어가 동작합니다. 셋 다 비어 있으면 모든 명령어가 거부됩니다.": "Leave blank to allow commands only in the notification channel above. If all three fields are empty, every command is rejected.", "받을 알림": "Notifications to receive", "꺼둔 종류는 아예 전송되지 않습니다.": "Disabled notification types will not be sent.", "전체 선택": "Select all", "전체 해제": "Clear all", "멘션": "Mentions", "놓치면 안 되는 알림에만 멘션을 붙이세요.": "Use mentions only for notifications you cannot afford to miss.", "멘션 대상": "Mention target", "역할을 멘션하려면 <@&역할ID> 형식으로 직접 입력합니다.": "To mention a role, enter its ID in the format <@&role_id>.", "@here — 접속 중인 사람만": "@here — online members only", "@everyone — 서버 전체": "@everyone — entire server", "멘션을 붙일 알림": "Notifications to mention", "아무것도 고르지 않으면 멘션 없이 전송됩니다.": "Notifications are sent without a mention if none are selected.", "이 알림이 꺼져 있습니다": "This notification is disabled", "고급": "Advanced", "전송이 밀렸을 때의 동작을 조정합니다.": "Configure what happens when delivery is delayed.", "알림 유효 시간 (분)": "Notification expiration (minutes)", "이 시간을 넘긴 알림은 뒷북이 되므로 전송하지 않고 버립니다. 연결이 오래 끊겼다가 복구됐을 때 지난 알림이 쏟아지는 걸 막습니다.": "Older notifications are discarded instead of being delivered late. This prevents a flood of stale alerts after a long outage.", "저장됨": "Saved", "전송됨": "Delivered", "폐기": "Dropped", "만료": "Expired", "연결됨": "Connected", "대기 중": "Waiting", "상태를 불러오지 못했습니다.": "Could not load status.",
        "방송 시작 감지": "Stream started", "녹화 시작": "Recording started", "녹화 완료": "Recording completed", "녹화 실패": "Recording failed", "X Spaces 감지": "X Space detected", "다시보기 다운로드 완료": "Video download completed", "다시보기 다운로드 실패": "Video download failed", "쿠키 만료": "Cookie expired", "신규 버전": "New version",
        "컬러 테마": "Color theme", "현재:": "Current:", "사용자 지정": "Custom", "페이지 타이틀": "Page title", "브라우저 탭 제목이 변경됩니다 (최대 32자)": "Changes the browser tab title (up to 32 characters).",
        "Chzzk (기본)": "Chzzk (default)", "블루": "Blue", "퍼플": "Purple", "오렌지": "Orange", "레드": "Red",
        "적용": "Apply", "탭 아이콘 (Favicon)": "Tab icon (favicon)", "브라우저 탭 좌측 아이콘이 변경됩니다.": "Changes the icon shown in the browser tab.",
        "이미지 업로드 (PNG · JPG · WEBP, 512KB 이하)": "Upload image (PNG · JPG · WEBP, up to 512 KB)", "외관 초기화 (기본값 복원)": "Reset appearance",
        "실시간 방송 관리": "Live stream management", "방송 상태를 확인하고 채널별 자동 다운로드와 녹화를 관리합니다.": "Monitor streams and manage automatic downloads and recordings by channel.",
        "프로그램 업데이트": "App updates", "현재 버전": "Current version", "최신 릴리즈": "Latest release", "업데이트 확인": "Check for updates", "v{version} 업데이트 하기": "Update to v{version}", "릴리즈 노트": "Release notes", "새로운 버전이 있습니다!": "A new version is available!", "최신 버전을 사용 중입니다.": "You are using the latest version.", "업데이트 확인에 실패했습니다.": "Could not check for updates.", "시스템 정보": "System information", "앱 이름": "App name", "불러오는 중…": "Loading…", "FFmpeg 버전": "FFmpeg version", "설치됨": "Installed", "버전을 확인할 수 없음": "Version unavailable", "설치되지 않음": "Not installed", "버전": "Version", "X Spaces 쿠키": "X Spaces cookies", "프로그램 정보": "About", "만든 사람": "Author", "저장소": "Repository", "라이선스": "License", "Copyright © 2026 {author}. 배포 라이선스: MIT.": "Copyright © 2026 {author}. Distributed under the MIT License.", "FFmpeg는 앱에 포함되지 않으며 별도의 라이선스를 따릅니다.": "FFmpeg is not bundled and is subject to its own license.",
        "감시 채널": "Monitored channels", "방송 중": "Live", "녹화 중": "Recording", "새로고침": "Refresh",
        "영상 다운로드": "Video downloads", "여러 플랫폼의 다시보기와 클립을 추가하고 다운로드 상태를 한곳에서 관리합니다.": "Add VODs and clips from multiple platforms and manage downloads in one place.",
        "진행 중": "Active", "대기": "Queued", "오류": "Errors", "전체": "All", "추가": "Add",
        "녹화 현황 분석": "Recording overview", "녹화 시간, 파일 용량, 채널 활동과 저장소 상태를 한눈에 파악합니다.": "See recording time, file sizes, channel activity, and storage at a glance.",
        "30초마다 갱신": "Refreshes every 30 sec", "통계 정보를 불러오는 중": "Loading statistics", "통계를 집계하고 있습니다": "Loading statistics…",
        "통계 정보를 불러오지 못했습니다": "Could not load statistics", "통계 조회 실패": "Could not load statistics", "통계 갱신에 실패했습니다. 이전 데이터를 표시합니다.": "Could not refresh statistics. Showing the previous data.", "설정을 불러오지 못했습니다": "Could not load settings", "설정을 불러오는 중": "Loading settings", "서버 연결을 확인한 뒤 다시 시도해 주세요.": "Check the server connection and try again.", "잠시만 기다려 주세요.": "Please wait a moment.", "다시 시도": "Try again",
        "채팅 로그를 불러오지 못했습니다.": "Could not load chat logs.", "메시지를 불러오지 못했습니다.": "Could not load messages.", "로그 목록을 불러오지 못했습니다.": "Could not load the log list.", "로그 내용을 불러오지 못했습니다.": "Could not load the log content.", "로그 갱신에 실패했습니다. 기존 내용을 표시합니다.": "Could not refresh logs. Showing the previous content.",
        "완료된 라이브 녹화 시간": "Completed live recording time", "완료된 녹화 용량": "Completed recording size", "완료된 라이브 파일 합계": "Total completed live files",
        "외부": "External", "디스크 사용률": "Disk usage", "여유 공간": "free", "채널별 기록": "Channel history",
        "라이브 감지는 최근 30일 기준": "Live detection over the last 30 days", "채널": "Channels", "아직 집계할 녹화가 없습니다": "No recordings to report yet",
        "첫 녹화가 완료되면 채널별 통계가 표시됩니다.": "Channel statistics will appear after the first recording completes.", "최근 녹화": "Recent recordings",
        "최근 완료된 10개 세션": "10 most recent completed sessions", "녹화 이력이 없습니다": "No recording history", "완료된 세션이 여기에 쌓입니다.": "Completed sessions will appear here.",
        "녹화": "Recordings", "라이브 감지": "Live detections", "총 시간": "Total time", "용량": "Size", "회": " sessions", "일": " days",
        "오디오 보관함": "Audio archive", "캡처한 X Spaces 스트림을 오래 보관할 수 있는 오디오 파일로 변환합니다.": "Convert captured X Spaces streams into audio files for long-term storage.",
        "다운로드 소스": "Download source", "라이브 채팅 아카이브": "Live chat archive", "채널별 채팅 기록을 검색하고, 녹화 세션의 원본 로그를 다운로드하세요.": "Search chat by channel and download original logs from recording sessions.",
        "시스템 로그": "System logs", "로그 파일 목록": "Log files", "로그 내용": "Log contents",
        "개": " items", "시간": "h", "분": "m", "파일 크기는 512KB 이하여야 합니다.": "The file must be 512 KB or smaller.",
        "라이브": "Live", "오프라인": "Offline", "채널 상태 필터": "Channel status filter", "즉시 스캔": "Scan now", "전체 중지": "Stop all",
        "채널 보기 방식": "Channel view", "카드로 보기": "Grid view", "목록으로 보기": "List view", "채널 태그": "Channel tags", "속도": "Speed", "비트레이트": "Bitrate",
        "드래그하거나 방향키를 눌러 채널 순서 변경": "Drag or use the arrow keys to reorder channels", "채널 제거": "Remove channel", "상태": "Status", "자동 녹화": "Auto-record", "다운로드 설정": "Download settings", "녹화 중단": "Stop recording",
        "저장 경로": "Storage path", "저장 위치": "Storage location", "저장 경로 복사": "Copy storage path", "저장 경로를 복사했습니다.": "Storage path copied.", "저장 경로를 복사하지 못했습니다.": "Could not copy the storage path.", "복사": "Copy", "최근": "Recent", "검토": "Review", "X Spaces 다운로드": "Download X Spaces",
        "녹화 시간": "Recording time", "방송 미리보기": "Live preview", "현재 방송 중이 아닙니다.": "This channel is currently offline.", "미리보기 크게 보기": "Expand preview", "미리보기를 불러오는 중": "Loading preview", "크게 보기": "Expand", "닫기": "Close",
        "채팅 로그를 선택해 내용을 확인하세요.": "Select a chat log to view its contents.", "로그 파일": "Log files", "채팅 내용": "Chat messages", "영상 URL": "Video URL",
        "YouTube": "YouTube", "외부 영상": "External video", "다시보기 URL 또는 클립 URL": "VOD or clip URL", "핸들(@username) 또는 동영상 ID": "YouTube handle (@username) or video ID", "다운로드할 영상 링크": "Video link to download",
        "YouTube 링크, @핸들 또는 11자리 동영상 ID를 입력해 주세요.": "Enter a YouTube link, @handle, or 11-character video ID.", "올바른 영상 주소를 입력해 주세요.": "Enter a valid video URL.", "Chzzk 다시보기 또는 클립 주소를 입력해 주세요.": "Enter a Chzzk VOD or clip URL.",
        "YouTube 링크, @핸들 또는 동영상 ID를 입력해 주세요.": "Enter a YouTube link, @handle, or video ID.", "지원되는 외부 영상 주소인지 확인해 주세요.": "Check that this is a supported video URL.", "다운로드 목록에 추가했습니다.": "Added to the download queue.", "영상 추가에 실패했습니다.": "Could not add the video.",
        "다운로드 시작": "Start download", "다운로드 중지": "Stop download", "중지": "Stop", "다시 다운로드": "Retry download", "다시 받기": "Retry", "목록 정리": "Clear list", "정리": "Clear",
        "대기·완료·오류 항목을 목록에서 삭제할까요? 진행 중이거나 일시정지한 항목은 유지됩니다.": "Remove queued, completed, and failed items? Active and paused downloads will remain.",
        "서비스 상태 확인": "Service status", "실시간 서비스 로그와 일자별 백업을 검색하고 서버 상태를 추적합니다.": "Search live service logs and daily backups to monitor server status.", "로그 초기화": "Clear logs",
        "X Spaces 주소": "X Spaces URL", "X Spaces 주소 또는 라이브 대시보드에서 저장한 재생 목록 주소를 붙여넣으세요.": "Paste an X Spaces URL or a playlist URL saved from the Live Dashboard.", "라이브 대시보드에서 자동 저장한 재생 목록 주소도 사용할 수 있습니다.": "Playlist URLs saved automatically by the Live Dashboard are also supported.",
        "영상 없이 효율적인 오디오 형식으로 저장됩니다.": "Saved as an efficient audio-only file.", "링크 유효 기간": "Link availability", "master playlist는 Space 종료 후 약 30일간 유효합니다.": "The master playlist is usually available for about 30 days after the Space ends.", "비공개 Space": "Private Spaces", "설정에서 X 쿠키 파일을 먼저 지정해 주세요.": "Set an X cookie file in Settings first.", "진행 상황과 저장된 파일은 모니터링의 다시보기 대시보드에서 확인할 수 있습니다.": "Check progress and saved files in the Video Dashboard under Monitoring.",
        "워크스페이스를 준비하고 있습니다": "Preparing your workspace",
        "Global Command Palette": "Global command palette", "검색하거나 명령어를 입력하세요...": "Search or enter a command…", "검색 결과가 없습니다.": "No results found.", "이동 (Navigation)": "Navigation",
        "일반 설정": "General settings", "일반 설정이 저장되었습니다.": "General settings saved.", "일반 설정 저장에 실패했습니다.": "Could not save general settings.", "라이브 저장 경로": "Live recording folder", "라이브 녹화 파일과 해당 방송의 채팅 로그가 저장됩니다.": "Live recordings and their chat logs are saved here.",
        "다시보기 저장 경로": "VOD download folder", "Chzzk 다시보기·클립과 외부 영상 다운로드가 저장됩니다.": "Chzzk VODs, clips, and external video downloads are saved here.", "감시 주기 (초)": "Monitoring interval (seconds)", "채널 라이브 상태를 확인하는 간격 (5~300초).": "How often to check whether channels are live (5–300 seconds).",
        "라이브 녹화 포맷": "Live recording format", "TS/MKV는 녹화 중단 시에도 파일이 유지됩니다. MP4는 라이브 녹화에 적합하지 않습니다.": "TS and MKV files remain usable if a recording is interrupted. MP4 is not recommended for live recording.", "TS — MPEG Transport Stream (권장)": "TS — MPEG Transport Stream (recommended)", "MP4 (권장하지 않음 — 라이브 중단 시 파일 손상 가능)": "MP4 (not recommended — may be damaged if a live recording stops)", "저장 중...": "Saving…", "일반 설정 저장": "Save general settings",
        "디렉토리를 불러올 수 없습니다.": "Could not load folders.", "폴더 선택": "Choose a folder", "드라이브 목록으로": "Show drives", "드라이브 선택": "Select a drive", "하위 폴더 없음": "No subfolders", "취소": "Cancel", "이 폴더 선택": "Select this folder", "폴더 찾아보기": "Browse folders", "찾아보기": "Browse", "경로 입력...": "Enter a path…",
        "영상 다운로드 설정": "Video download settings", "동시 다운로드 개수": "Concurrent downloads", "한 번에 다운로드할 수 있는 최대 영상 개수 (1~10개)": "Maximum number of videos to download at once (1–10).", "영상 다운로드 품질": "Video quality", "영상 다운로드 시 기본으로 사용할 화질": "Default quality for video downloads.", "최고 화질": "Best quality", "최대 다운로드 속도 (MB/s)": "Maximum download speed (MB/s)", "0 = 무제한, 네트워크 대역폭 제한 시 사용": "0 = unlimited. Set a limit to save bandwidth.",
        "영상 파일 형식": "Video file format", "MP4 — MPEG-4 (권장)": "MP4 — MPEG-4 (recommended)", "다시보기와 클립은 MP4가 여러 기기에서 잘 재생됩니다. 영상과 음성을 합칠 때 ffmpeg를 사용합니다.": "MP4 works on most devices for VODs and clips. ffmpeg is used to merge audio and video.", "미완료 영상 파일 보관 (.part)": "Keep incomplete video files (.part)", "미완료 영상 파일 보관": "Keep incomplete video files", "취소 또는 오류가 발생해도 미완료 파일을 보관합니다.": "Keep partial files when a download is canceled or fails.", "취소하거나 오류가 발생하면 미완료 파일을 삭제합니다.": "Delete partial files when a download is canceled or fails.", "영상 파일명 형식": "Video filename format",
        "{name}, {title}, {date_year}, {date_month}, {date_day}, {date_hour}, {date_minute}, {date_second}, {id}, {extractor}, {upload_date}, {download_date}, {quality}를 사용할 수 있습니다. 날짜와 시각은 다운로드 시작 기준이며 확장자는 자동으로 붙습니다.": "Available fields: {name}, {title}, {date_year}, {date_month}, {date_day}, {date_hour}, {date_minute}, {date_second}, {id}, {extractor}, {upload_date}, {download_date}, and {quality}. Date and time use the download start time. The extension is added automatically.", "영상 다운로드 설정 저장": "Save video download settings", "영상 다운로드 설정을 저장했습니다.": "Video download settings saved.", "영상 다운로드 설정 저장에 실패했습니다.": "Could not save video download settings.",
        "라이브 다운로드 설정": "Live recording settings", "라이브 품질": "Live recording quality", "라이브 녹화에 사용할 yt-dlp 화질입니다.": "yt-dlp quality to use for live recordings.", "자동 재시도 횟수": "Automatic retries", "라이브 녹화 중단 시 자동 재시도 횟수.": "How many times to retry after a live recording is interrupted.", "Chzzk 스트림 획득 방법": "Chzzk stream source", "타임머신을 강제 사용하며, 사용할 수 없으면 녹화 요청을 실패 처리합니다.": "Always use Time Machine. If unavailable, the recording request fails.", "타임머신 API를 먼저 요청하고, 사용할 수 없으면 기본 스트림으로 자동 전환합니다.": "Try the Time Machine API first, then fall back to the standard stream if unavailable.", "Chzzk 기본 API에서 yt-dlp가 선택한 라이브 스트림을 사용합니다.": "Use the live stream selected by yt-dlp through the standard Chzzk API.",
        "기본 스트림 사용": "Use standard stream", "가능하면 타임머신 사용": "Use Time Machine when available", "강제로 타임머신 사용": "Always use Time Machine", "스트림 시작 오프셋 (초)": "Stream start offset (seconds)", "타임머신이 제공하는 스트림의 시작점에서 건너뛸 시간입니다. 0이면 사용 가능한 가장 앞부분부터 받습니다.": "Skip this much time from the start of a Time Machine stream. Use 0 to start at the earliest available point.", "라이브 미리보기 이미지 저장": "Save live preview images", "Chzzk 라이브 썸네일을 녹화 파일 옆에 저장합니다.": "Save the Chzzk live thumbnail next to the recording.", "미리보기 이미지를 별도 파일로 저장하지 않습니다.": "Do not save preview images as separate files.",
        "라이브 파일명 형식": "Live recording filename format", "{name}/{channel_name}, {title}/{live_title}, {channel_uid}, {category}, {date_year}, {live_date_year}, {download_date_year}, {live_date_month}, {live_date_day}, {live_date_hour}, {live_date_minute}, {live_date_second}, {quality}, {extension} 사용 가능. 확장자는 자동 추가됩니다.": "Available fields: {name}/{channel_name}, {title}/{live_title}, {channel_uid}, {category}, {date_year}, {live_date_year}, {download_date_year}, {live_date_month}, {live_date_day}, {live_date_hour}, {live_date_minute}, {live_date_second}, {quality}, and {extension}. The extension is added automatically.", "라이브 설정 저장": "Save live settings", "라이브 설정이 저장되었습니다.": "Live settings saved.", "라이브 설정 저장에 실패했습니다.": "Could not save live settings.", "실시간 채팅 설정": "Live chat settings", "라이브 채팅 저장": "Save live chat", "녹화 중 채팅을 JSONL 파일로 자동 저장합니다.": "Automatically save chat during recordings to JSONL files.", "라이브 채팅을 저장하지 않습니다.": "Do not save live chat.", "채팅 설정 저장": "Save chat settings", "채팅 설정이 저장되었습니다.": "Chat settings saved.", "채팅 설정 저장에 실패했습니다.": "Could not save chat settings.",
    },
    ja: {
        "시작 시 저장된 CDN 설정 적용": "開始時に保存済みCDN設定を適用",
        "영상 정보를 가져오지 못했습니다. 해당 항목에서 다시 조회해 주세요.": "動画情報を取得できませんでした。この項目を再取得してください。",
        "CHZZK VOD 준비 목록": "CHZZK VOD準備リスト",
        "CHZZK 다시보기 URL을 여기에 놓으세요.": "CHZZK VODのURLをここにドロップしてください。",
        "링크를 놓거나 여러 URL을 줄바꿈으로 입력하세요. 등록 후 화질을 선택할 수 있습니다.": "リンクをドロップするか、URLを改行で入力してください。登録後に画質を選べます。",
        "CHZZK 다시보기 URL 목록": "CHZZK VOD URLリスト",
        "VOD 등록": "VODを登録",
        "전체 다운로드 시작": "すべてダウンロード開始",
        "지원하지 않는 주소": "未対応のURL",
        "CHZZK 다시보기 주소를 입력해 주세요.": "CHZZK VODのURLを入力してください。",
        "한 번에 최대 100개의 URL을 등록할 수 있습니다.": "一度に登録できるURLは100件までです。",
        "이미 등록된 VOD입니다.": "このVODは登録済みです。",
        "동시 다운로드 제한은 서버 설정을 따릅니다.": "同時ダウンロード数はサーバー設定に従います。",
        "정보 조회 중": "情報取得中",
        "정보 조회 실패": "情報取得失敗",
        "다운로드 준비 완료": "ダウンロード準備完了",
        "병합 중": "結合中",
        "검증 중": "検証中",
        "취소됨": "キャンセル済み",
        "영상별 화질 선택": "動画ごとの画質選択",
        "기본 화질이 제공되지 않아 사용 가능한 화질을 선택했습니다.": "既定の画質がないため、利用可能な画質を選択しました。",
        "정보 다시 조회": "情報を再取得",
        "완료 목록 정리": "完了履歴を整理",
        "완료된 작업 이력만 정리합니다. 저장된 영상 파일은 삭제하지 않습니다.": "完了した履歴のみ整理します。保存済み動画は削除しません。",
        "영상 파일은 삭제하지 않습니다.": "動画ファイルは削除しません。",
        "이력 제거": "履歴を削除",
        "작업 이력을 제거했습니다.": "作業履歴を削除しました。",
        "정보 조회를 시작했습니다.": "情報取得を開始しました。",
        "화질을 변경했습니다.": "画質を変更しました。",
        "다운로드를 시작했습니다.": "ダウンロードを開始しました。",
        "녹화 시작하기": "録画を開始", "상세 보기": "詳細", "상세 접기": "詳細を閉じる", "태그": "タグ", "녹화 중지": "録画停止",
        "시청자": "視聴者",
        "채널 관리": "チャンネル管理",
        "위로 이동": "上へ移動", "아래로 이동": "下へ移動", "명령 복사": "コマンドをコピー", "메시지 갱신에 실패했습니다. 이전 내용을 표시합니다.": "メッセージを更新できませんでした。以前の内容を表示しています。",
        "다른 채널": "その他のチャンネル",
        "채팅 기록을 불러오는 중": "チャット履歴を読み込み中",
        "다운로드 목록을 불러오는 중": "ダウンロード一覧を読み込み中",
        "로그 목록을 불러오는 중": "ログ一覧を読み込み中",
        "통계를 불러오는 중": "統計を読み込み中",
        "다운로드한 다시보기, 클립 및 영상이 저장됩니다.": "ダウンロードしたアーカイブ、クリップ、動画を保存します。",
        "등록한 채널의 방송 상태와 녹화를 관리합니다.": "登録したチャンネルの配信状況と録画を管理します。",
        "등록된 채널이 없습니다.": "登録済みのチャンネルはありません。",
        "채널을 추가하면 방송 상태를 확인하고 자동으로 녹화할 수 있습니다.": "チャンネルを追加すると、配信状況の確認と自動録画ができます。",
        "채널 상세 보기": "チャンネルの詳細",
        "녹화 정보": "録画情報",
        "다시보기, 클립 및 지원되는 영상을 다운로드합니다.": "アーカイブ、クリップ、対応する動画をダウンロードします。",
        "다운로드 상태 필터": "ダウンロード状態の絞り込み",
        "해당 상태의 다운로드가 없습니다.": "この状態のダウンロードはありません。",
        "다른 상태를 선택해 작업을 확인하세요.": "別の状態を選択してダウンロードを確認してください。",
        "다운로드를 완료하지 못했습니다. 다시 시도하거나 영상 주소와 인증 설정을 확인하세요.": "ダウンロードに失敗しました。再試行するか、動画のURLと認証設定を確認してください。",
        "다운로드 목록을 불러오지 못했습니다. 잠시 후 다시 시도하세요.": "ダウンロード一覧を読み込めませんでした。しばらくしてから再試行してください。",
        "다운로드 진행률": "ダウンロードの進捗",
        "녹화, 다운로드, 인증, 알림 및 애플리케이션 동작을 구성합니다.": "録画、ダウンロード、認証、通知、アプリの動作を設定します。",
        "라이브 녹화 설정": "ライブ録画の設定",
        "Chzzk 녹화 방식": "Chzzkの録画方式",
        "서버 주소": "サーバーアドレス",
        "화면을 표시하지 못했습니다.": "画面を表示できませんでした。",
        "페이지를 새로고침하거나 라이브 화면으로 돌아가세요.": "ページを更新するか、ライブ画面に戻ってください。",
        "라이브로 이동": "ライブに戻る",
        "페이지 이동": "ページに移動",
        "페이지 검색...": "ページを検索...",
        "채팅 내용 검색": "チャット内容を検索",
        "닉네임 검색": "ニックネームを検索",
        "같이보기만 녹화": "ウォッチパーティーのみ録画",
        "같이보기 제외하고 녹화": "ウォッチパーティーを除外して録画",
        "서버 연결이 끊겼습니다. 다시 연결하는 중입니다.": "サーバーへの接続が切れました。再接続しています。",

        "라이브 녹화·영상 다운로드": "ライブ録画・動画ダウンロード",
        "시작 전에": "始める前に",
        "실시간": "リアルタイム",
        "오류 세부 정보": "エラーの詳細",
        "대기 중·완료·실패한 작업만 목록에서 삭제합니다. 진행 중이거나 일시정지한 작업과 저장된 파일은 유지됩니다.": "待機中・完了・失敗したタスクのみ削除します。進行中または一時停止中のタスクと保存済みファイルは残ります。",

        "다시보기·클립 링크": "アーカイブ・クリップのURL",
        "@핸들 또는 동영상 ID": "@ハンドルまたは動画ID",
        "영상 링크 입력": "動画URLを入力",
        "Chzzk 다시보기와 클립, YouTube와 외부 영상을 추가하고 다운로드 상태를 관리합니다.": "Chzzkのアーカイブやクリップ、YouTubeなどの動画を追加し、ダウンロード状況を確認できます。",

        "같이보기 방송은 자동 녹화하지 않도록 설정되어 있습니다.": "ウォッチパーティー配信は自動録画しない設定です。",
        "같이보기 방송만 녹화하도록 설정되어 있어 이 방송은 저장하지 않습니다.": "ウォッチパーティーのみ録画する設定のため、この配信は保存しません。",
        "방송의 같이보기 태그가 설정한 태그와 일치하지 않습니다.": "配信のウォッチパーティータグが設定したタグと一致しません。",
        "방송 태그가 설정한 녹화 조건과 일치하지 않습니다.": "配信タグが録画条件に一致しません。",
        "Chzzk 다시보기와 클립, YouTube 및 외부 영상을 추가하고 다운로드 상태를 관리합니다.": "Chzzkのアーカイブやクリップ、YouTubeなどの動画を追加し、ダウンロード状況を確認できます。",
        "아직 추가한 영상이 없습니다": "動画はまだ追加されていません",
        "영상 주소를 추가하면 다운로드 진행 상황과 저장 위치를 확인할 수 있습니다.": "動画URLを追加すると、ダウンロード状況と保存先を確認できます。",

        "채널 녹화 설정": "チャンネル録画設定",
        "라이브 채널 추가": "ライブチャンネルを追加",
        "현재 방송 태그": "現在の配信タグ",
        "Chzzk 같이보기 방송": "Chzzkウォッチパーティー配信",
        "Chzzk의 같이보기 정보와 방송 태그를 확인합니다. 변경 사항은 다음 자동 녹화부터 적용되며, 진행 중인 녹화와 수동 녹화에는 영향을 주지 않습니다.": "Chzzkのウォッチパーティー情報と配信タグを確認します。変更は次回の自動録画から適用され、録画中や手動録画には影響しません。",
        "설정한 녹화 조건에 맞지 않는 방송입니다.": "設定した録画条件に一致しない配信です。",
        "자동 녹화 보류": "自動録画保留中",
        "녹화 설정": "録画設定",
        "채팅 기록": "チャット履歴",
        "진행 상황과 저장한 파일은 영상 다운로드 화면에서 확인할 수 있습니다.": "進行状況と保存したファイルは動画ダウンロード画面で確認できます。",
        "다운로드를 완료하지 못했습니다. 오류 세부 정보": "ダウンロードを完了できませんでした。エラーの詳細",
        "화질": "解像度",
        "다운로드 속도 제한 (MB/s)": "ダウンロード速度の上限（MB/s）",
        "0으로 설정하면 속도 제한 없이 다운로드합니다.": "0に設定すると速度制限なしでダウンロードします。",
        "대기 중·완료·실패한 항목을 목록에서 삭제할까요? 진행 중이거나 일시정지한 항목은 유지됩니다.": "待機中・完了・失敗した項目を一覧から削除しますか？進行中または一時停止中の項目は残ります。",
        "다운로드 목록에서 {count}개 항목을 삭제했습니다.": "ダウンロード一覧から{count}件を削除しました。",
        "목록 정리에 실패했습니다.": "ダウンロード一覧を整理できませんでした。",
        "작업 순서 변경에 실패했습니다.": "タスクの順序を変更できませんでした。",

        "다운로드 관리": "ダウンロード管理", "방송 상태를 확인하고 채널별 자동 녹화와 녹화 조건을 관리합니다.": "配信状況を確認し、チャンネルごとの自動録画と録画条件を管理します。", "이 채널의 녹화 조건에 맞지 않는 방송입니다.": "この配信はチャンネルの録画条件に一致しません。", "같이보기 정보를 확인하고 있습니다.": "ウォッチパーティー情報を確認しています。", "자동 녹화 대기": "自動録画待ち", "자동 녹화 꺼짐": "自動録画オフ",
        "다운로드를 취소할까요?": "ダウンロードをキャンセルしますか？", "‘{title}’ 다운로드를 취소합니다.": "「{title}」のダウンロードをキャンセルします。", "다운로드 취소": "ダウンロードをキャンセル", "다운로드 취소를 요청했습니다.": "ダウンロードのキャンセルをリクエストしました。", "다운로드를 취소하지 못했습니다.": "ダウンロードをキャンセルできませんでした。", "다운로드를 다시 시작할까요?": "ダウンロードを再試行しますか？", "‘{title}’을(를) 다시 다운로드합니다.": "「{title}」をもう一度ダウンロードします。", "다운로드를 다시 시작했습니다.": "ダウンロードを再開しました。", "다운로드를 다시 시작하지 못했습니다.": "ダウンロードを再開できませんでした。", "다운로드를 일시정지했습니다.": "ダウンロードを一時停止しました。", "다운로드를 일시정지하지 못했습니다.": "ダウンロードを一時停止できませんでした。", "다운로드를 재개했습니다.": "ダウンロードを再開しました。", "다운로드를 재개하지 못했습니다.": "ダウンロードを再開できませんでした。", "다운로드 목록": "ダウンロード一覧", "남은 시간": "残り時間", "일시정지하기": "一時停止", "재개": "再開", "폴더 열기": "フォルダーを開く", "파일 위치 열기": "ファイルの場所を開く", "다운로드 중": "ダウンロード中", "일시정지": "一時停止", "완료": "完了", "취소 중": "キャンセル中", "실패": "失敗",
        "모든 방송 녹화": "すべての配信を録画", "같이보기 방송만 녹화": "ウォッチパーティーのみ録画", "같이보기 방송 제외": "ウォッチパーティーを除外",
        "기본 녹화 조건": "基本録画条件", "기본 녹화 조건을 저장했습니다.": "基本録画条件を保存しました。", "녹화 조건을 저장하지 못했습니다.": "録画条件を保存できませんでした。", "녹화 조건을 불러오지 못했습니다.": "録画条件を読み込めませんでした。",
        "같이보기 태그": "ウォッチパーティータグ", "‘같이보기’는 전체 같이보기를 선택합니다. 특정 콘텐츠 태그는 쉼표로 구분하세요.": "「ウォッチパーティー」で全件に一致します。特定のコンテンツタグはカンマで区切ってください。", "예: 같이보기": "例: ウォッチパーティー", "Chzzk의 같이보기 정보와 방송 태그를 기준으로 판단합니다. 채널별 설정이 기본값보다 우선합니다.": "Chzzkのウォッチパーティー情報と配信タグを基準に判定します。チャンネルごとの設定が優先されます。", "기본 조건 저장": "基本条件を保存", "현재 기본값": "現在の既定値", "방송이 시작되고 녹화 조건에 맞으면 자동으로 저장합니다.": "配信が始まり、録画条件に一致すると自動で録画します。", "녹화 조건": "録画条件", "이 채널에만 적용합니다.": "このチャンネルのみに適用します。", "기본 조건 사용": "既定の条件を使用",
        "채널 영상 목록 불러오기를 시작했습니다.": "チャンネル動画の読み込みを開始しました。", "채널 영상 목록 불러오기 대기 중": "チャンネル動画の読み込み待ち", "채널 영상 목록을 불러오는 중": "チャンネル動画を読み込み中", "채널 영상 목록 불러오기 완료": "チャンネル動画を読み込みました", "채널 영상 목록 불러오기 중지됨": "チャンネル動画の読み込みを停止しました", "채널 영상 목록을 불러오지 못했습니다.": "チャンネル動画を読み込めませんでした。", "목록 불러오기를 중지해도 이미 추가된 영상은 유지됩니다.": "読み込みを停止しても、追加済みの動画は残ります。", "불러오기 중지": "読み込みを停止",
        "라이브 저장 위치": "ライブ録画の保存先", "영상 저장 위치": "動画の保存先", "라이브 확인 주기 (초)": "配信状況の確認間隔（秒）", "등록한 채널의 방송 상태를 확인하는 간격입니다 (5~300초).": "登録したチャンネルの配信状況を確認する間隔です（5～300秒）。", "라이브 녹화 파일 형식": "ライブ録画ファイル形式", "TS와 MKV는 녹화가 중단되어도 재생할 수 있습니다. MP4는 중단 시 파일이 손상될 수 있습니다.": "TSとMKVは録画が中断しても再生できます。MP4は中断時にファイルが破損する場合があります。", "기본 화질": "既定の画質", "영상 다운로드에 사용할 기본 해상도입니다.": "動画ダウンロードの既定の解像度です。", "라이브 녹화 화질": "ライブ録画の画質", "녹화할 해상도를 선택합니다. 높은 해상도일수록 저장 공간을 더 사용합니다.": "録画する解像度を選びます。高解像度ほどストレージを多く使用します。", "녹화 자동 재시도 횟수": "録画の自動再試行回数", "연결이 끊기거나 녹화에 실패했을 때 다시 시도할 횟수입니다.": "接続が切れた場合や録画に失敗した場合に再試行する回数です。", "MP4는 대부분의 기기와 플레이어에서 재생할 수 있습니다.": "MP4はほとんどの端末やプレーヤーで再生できます。",
        "더 보기": "もっと見る",
        "YouTube 쿠키를 등록했습니다.": "YouTubeのCookieを登録しました。",
        "선택 사항 · 공개 영상은 쿠키 없이 다운로드합니다. 로그인·연령 제한·멤버십 확인이 필요한 경우에만 등록한 쿠키를 사용합니다.": "任意。公開動画はCookieなしでダウンロードします。登録したCookieは、ログイン・年齢確認・メンバーシップが必要な場合のみ使用します。",
        "YouTube 쿠키 내보내기 안내": "YouTube Cookieのエクスポート方法",
        "채널 영상 수집을 시작했습니다.": "チャンネル動画の取得を開始しました。",
        "채널 영상 수집 대기 중": "チャンネル動画の取得待ち",
        "채널 영상을 불러오는 중": "チャンネル動画を取得中",
        "채널 영상 수집 완료": "チャンネル動画の取得完了",
        "채널 영상 수집 중지됨": "チャンネル動画の取得を停止しました",
        "채널 영상 수집 실패": "チャンネル動画の取得に失敗しました",
        "추가한 영상": "追加した動画",
        "이미 목록에 있는 영상": "追加済みの動画",
        "찾은 영상부터 다운로드합니다. 수집을 중지해도 추가된 영상은 유지됩니다.": "見つかった動画からダウンロードします。取得を停止しても追加済みの動画は残ります。",
        "수집 중지": "取得を停止",
        "영상을 찾으면 이곳에 표시됩니다.": "見つかった動画がここに表示されます。",
        "요청에 실패했습니다.": "リクエストに失敗しました。",
        "모니터링": "モニタリング", "미디어 허브": "メディアハブ", "워크스페이스": "ワークスペース",
        "라이브 대시보드": "ライブダッシュボード", "다시보기 대시보드": "動画ダッシュボード", "통계": "統計", "로그": "ログ", "설정": "設定",
        "알림 센터": "通知センター", "최근 앱 이벤트": "最近のアプリイベント", "모두 지우기": "すべて削除", "아직 알림 내역이 없습니다.": "通知はありません。",
        "메뉴 열기": "メニューを開く", "메뉴 닫기": "メニューを閉じる", "빠른 이동": "クイック移動", "다운로드": "ダウンロード", "주 메뉴": "メインメニュー", "본문으로 이동": "本文へ移動",
        "프로그램 설정": "アプリ設定", "녹화 방식과 인증, 알림, 화면 테마 및 시스템 동작을 구성합니다.": "録画、認証、通知、外観、システム動作を設定します。",
        "일반": "一般", "인증": "認証", "알림": "通知", "외관": "外観", "시스템": "システム", "정보": "情報",
        "외관 설정": "外観設定", "언어": "言語", "앱에서 사용할 언어를 선택합니다.": "アプリで使用する言語を選択します。",
        "Chzzk": "Chzzk", "만료/미설정": "期限切れ／未設定", "NID_AUT 쿠키 값 입력...": "NID_AUT Cookieの値を入力…", "NID_SES 쿠키 값 입력...": "NID_SES Cookieの値を入力…", "유효함": "有効", "업로드됨": "アップロード済み", "없음": "なし", "확인 중...": "確認中…", "상태 확인": "状態を確認", "저장": "保存", "검증": "検証", "개발자 페이지": "開発者ページ", "에서 앱을 등록하고 발급받은 API v2 인증 정보를 입력하세요.": "でアプリを登録し、発行されたAPI v2の認証情報を入力してください。", "Client ID": "Client ID", "Client Secret": "Client Secret", "X Spaces 녹화 시 사용할 Netscape 형식 쿠키 파일을 업로드하세요.": "X Spacesの録画に使用するNetscape形式のCookieファイルをアップロードしてください。", "파일 선택": "ファイルを選択", "업로드 중...": "アップロード中…", "삭제": "削除", "쿠키 파일이 삭제되었습니다.": "Cookieファイルを削除しました。", "쿠키 파일 삭제에 실패했습니다.": "Cookieファイルを削除できませんでした。", "X Spaces 인증 파일이 준비되었습니다.": "X Spacesの認証ファイルを使用できます。",
        "연결 상태": "接続状態", "알림이 실제로 나가고 있는지 여기서 확인합니다.": "通知が実際に配信されているか確認できます。", "상태 새로고침": "状態を更新", "테스트 발송": "テスト送信", "Bot 토큰 + 채널 ID 또는 Webhook URL 중 하나는 설정해야 알림이 전송됩니다.": "通知を送信するには、BotトークンとチャンネルID、またはWebhook URLを設定してください。", "Discord 채널 설정에서 URL 하나만 복사하면 끝납니다. 알림만 받을 거라면 이것으로 충분합니다.": "Discordチャンネルの設定からURLをコピーするだけで完了します。通知を受け取るだけならこれで十分です。", "권장": "おすすめ", "설정됨": "設定済み", "미설정": "未設定", "설정됨 — 변경하려면 입력": "設定済み — 変更するには新しい値を入力", "Discord 채널 설정 → 연동 → 웹후크에서 만듭니다. Bot을 만들지 않아도 모든 알림이 정상 동작합니다.": "Discordのチャンネル設定 → 連携サービス → ウェブフックで作成します。Botを作成しなくても通知を利用できます。", "디스코드에서 원격 제어까지 하려면": "Discordから録画を操作する場合", "Bot을 등록하면 /status, /start, /stop 같은 슬래시 커맨드로 녹화를 제어할 수 있습니다. 알림만 받을 거라면 설정하지 않아도 됩니다.": "Botを登録すると、/status、/start、/stopなどのスラッシュコマンドで録画を操作できます。通知だけなら設定は不要です。", "비워두면 기존 토큰을 유지합니다. Discord Developer Portal에서 발급받으세요. 토큰 변경은 재시작 후 적용됩니다.": "空欄の場合は現在のトークンを維持します。Discord Developer Portalで取得してください。変更は再起動後に反映されます。", "알림 채널 ID": "通知チャンネルID", "Discord에서 개발자 모드를 켠 뒤 채널 우클릭 → 'ID 복사'로 얻은 숫자입니다.": "Discordで開発者モードを有効にし、チャンネルを右クリックして「IDをコピー」すると取得できます。", "명령어 허용 사용자 ID": "コマンドを許可するユーザーID", "쉼표로 구분합니다. 비워두면 사용자 제한 없이 채널 조건만 적용됩니다.": "カンマ区切りで入力します。空欄の場合、ユーザー制限はなくチャンネル条件のみ適用されます。", "명령어 허용 채널 ID": "コマンドを許可するチャンネルID", "비워두면 위 알림 채널에서만 명령어가 동작합니다. 셋 다 비어 있으면 모든 명령어가 거부됩니다.": "空欄の場合、上記の通知チャンネルでのみコマンドを使用できます。3項目すべてが空欄の場合、すべてのコマンドが拒否されます。", "받을 알림": "受け取る通知", "꺼둔 종류는 아예 전송되지 않습니다.": "オフにした種類の通知は送信されません。", "전체 선택": "すべて選択", "전체 해제": "すべて解除", "멘션": "メンション", "놓치면 안 되는 알림에만 멘션을 붙이세요.": "見逃せない通知にだけメンションを付けましょう。", "멘션 대상": "メンション先", "역할을 멘션하려면 <@&역할ID> 형식으로 직접 입력합니다.": "ロールにメンションするには、<@&role_id>形式でIDを入力してください。", "@here — 접속 중인 사람만": "@here — オンラインのメンバー", "@everyone — 서버 전체": "@everyone — サーバー全員", "멘션을 붙일 알림": "メンションを付ける通知", "아무것도 고르지 않으면 멘션 없이 전송됩니다.": "何も選ばない場合、メンションなしで送信されます。", "이 알림이 꺼져 있습니다": "この通知はオフです", "고급": "詳細設定", "전송이 밀렸을 때의 동작을 조정합니다.": "通知の配信が遅れた場合の動作を設定します。", "알림 유효 시간 (분)": "通知の有効期限（分）", "이 시간을 넘긴 알림은 뒷북이 되므로 전송하지 않고 버립니다. 연결이 오래 끊겼다가 복구됐을 때 지난 알림이 쏟아지는 걸 막습니다.": "この時間を過ぎた通知は古いため破棄し、配信しません。長時間の接続断のあとに古い通知が一度に届くのを防ぎます。", "저장됨": "保存済み", "전송됨": "配信済み", "폐기": "破棄", "만료": "期限切れ", "연결됨": "接続済み", "대기 중": "待機中", "상태를 불러오지 못했습니다.": "状態を読み込めませんでした。",
        "방송 시작 감지": "配信開始を検出", "녹화 시작": "録画開始", "녹화 완료": "録画完了", "녹화 실패": "録画失敗", "X Spaces 감지": "X Spacesを検出", "다시보기 다운로드 완료": "アーカイブのダウンロード完了", "다시보기 다운로드 실패": "アーカイブのダウンロード失敗", "쿠키 만료": "Cookieの期限切れ", "신규 버전": "新しいバージョン",
        "컬러 테마": "カラーテーマ", "현재:": "現在:", "사용자 지정": "カスタム", "페이지 타이틀": "ページタイトル", "브라우저 탭 제목이 변경됩니다 (최대 32자)": "ブラウザーのタブ名を変更します（最大32文字）。",
        "Chzzk (기본)": "Chzzk（デフォルト）", "블루": "ブルー", "퍼플": "パープル", "오렌지": "オレンジ", "레드": "レッド",
        "적용": "適用", "탭 아이콘 (Favicon)": "タブアイコン（ファビコン）", "브라우저 탭 좌측 아이콘이 변경됩니다.": "ブラウザータブのアイコンを変更します。",
        "이미지 업로드 (PNG · JPG · WEBP, 512KB 이하)": "画像をアップロード（PNG・JPG・WEBP、512KB以下）", "외관 초기화 (기본값 복원)": "外観をリセット",
        "실시간 방송 관리": "ライブ配信管理", "방송 상태를 확인하고 채널별 자동 다운로드와 녹화를 관리합니다.": "配信状況を確認し、チャンネルごとの自動ダウンロードと録画を管理します。",
        "프로그램 업데이트": "アプリの更新", "현재 버전": "現在のバージョン", "최신 릴리즈": "最新リリース", "업데이트 확인": "更新を確認", "v{version} 업데이트 하기": "v{version}に更新", "릴리즈 노트": "リリースノート", "새로운 버전이 있습니다!": "新しいバージョンがあります！", "최신 버전을 사용 중입니다.": "最新バージョンを使用しています。", "업데이트 확인에 실패했습니다.": "更新を確認できませんでした。", "시스템 정보": "システム情報", "앱 이름": "アプリ名", "불러오는 중…": "読み込み中…", "FFmpeg 버전": "FFmpegのバージョン", "설치됨": "インストール済み", "버전을 확인할 수 없음": "バージョンを確認できません", "설치되지 않음": "未インストール", "버전": "バージョン", "X Spaces 쿠키": "X SpacesのCookie", "프로그램 정보": "アプリ情報", "만든 사람": "作成者", "저장소": "リポジトリ", "라이선스": "ライセンス", "Copyright © 2026 {author}. 배포 라이선스: MIT.": "Copyright © 2026 {author}. MIT Licenseで配布されています。", "FFmpeg는 앱에 포함되지 않으며 별도의 라이선스를 따릅니다.": "FFmpegは同梱されていません。別途ライセンスが適用されます。",
        "감시 채널": "監視中のチャンネル", "방송 중": "配信中", "녹화 중": "録画中", "새로고침": "更新",
        "영상 다운로드": "動画ダウンロード", "여러 플랫폼의 다시보기와 클립을 추가하고 다운로드 상태를 한곳에서 관리합니다.": "複数のプラットフォームから動画やクリップを追加し、ダウンロード状況をまとめて管理します。",
        "진행 중": "進行中", "대기": "待機中", "오류": "エラー", "전체": "すべて", "추가": "追加",
        "녹화 현황 분석": "録画状況", "녹화 시간, 파일 용량, 채널 활동과 저장소 상태를 한눈에 파악합니다.": "録画時間、ファイル容量、チャンネルの活動、ストレージ状況を確認できます。",
        "30초마다 갱신": "30秒ごとに更新", "통계 정보를 불러오는 중": "統計を読み込み中", "통계를 집계하고 있습니다": "統計を集計しています…",
        "통계 정보를 불러오지 못했습니다": "統計を読み込めませんでした", "통계 조회 실패": "統計を読み込めませんでした", "통계 갱신에 실패했습니다. 이전 데이터를 표시합니다.": "統計を更新できませんでした。前回のデータを表示しています。", "설정을 불러오지 못했습니다": "設定を読み込めませんでした", "설정을 불러오는 중": "設定を読み込み中", "서버 연결을 확인한 뒤 다시 시도해 주세요.": "サーバーの接続を確認して、もう一度お試しください。", "잠시만 기다려 주세요.": "しばらくお待ちください。", "다시 시도": "再試行",
        "채팅 로그를 불러오지 못했습니다.": "チャットログを読み込めませんでした。", "메시지를 불러오지 못했습니다.": "メッセージを読み込めませんでした。", "로그 목록을 불러오지 못했습니다.": "ログ一覧を読み込めませんでした。", "로그 내용을 불러오지 못했습니다.": "ログの内容を読み込めませんでした。", "로그 갱신에 실패했습니다. 기존 내용을 표시합니다.": "ログを更新できませんでした。前回の内容を表示しています。",
        "활성 녹화": "録画中", "용량 확인 기준 경로": "ストレージの保存先",
        "완료된 라이브 녹화 시간": "ライブ録画時間", "완료된 녹화 용량": "録画ファイル容量", "완료된 라이브 파일 합계": "ライブ録画ファイル合計",
        "외부": "外部", "디스크 사용률": "ディスク使用率", "여유 공간": "空き", "채널별 기록": "チャンネル別履歴",
        "라이브 감지는 최근 30일 기준": "過去30日間のライブ検出", "채널": "チャンネル", "아직 집계할 녹화가 없습니다": "集計できる録画はありません",
        "첫 녹화가 완료되면 채널별 통계가 표시됩니다.": "最初の録画が完了すると、チャンネル別の統計が表示されます。", "최근 녹화": "最近の録画",
        "최근 완료된 10개 세션": "最近完了した10件", "녹화 이력이 없습니다": "録画履歴はありません", "완료된 세션이 여기에 쌓입니다.": "完了したセッションがここに表示されます。",
        "녹화": "録画", "라이브 감지": "ライブ検出", "총 시간": "合計時間", "용량": "容量", "회": "回", "일": "日",
        "오디오 보관함": "オーディオアーカイブ", "캡처한 X Spaces 스트림을 오래 보관할 수 있는 오디오 파일로 변환합니다.": "保存したX Spacesの配信を、長期保管できる音声ファイルに変換します。",
        "다운로드 소스": "ダウンロード元", "라이브 채팅 아카이브": "ライブチャットアーカイブ", "채널별 채팅 기록을 검색하고, 녹화 세션의 원본 로그를 다운로드하세요.": "チャンネルごとのチャット履歴を検索し、録画セッションの元ログをダウンロードします。",
        "시스템 로그": "システムログ", "로그 파일 목록": "ログファイル", "로그 내용": "ログ内容", "7개 항목": "7項目", "저장하지 않은 변경사항": "未保存の変更", "업데이트 가능": "アップデートがあります", "설정 탭": "設定タブ",
        "개": "件", "파일 크기는 512KB 이하여야 합니다.": "ファイルサイズは512KB以下にしてください。",
        "라이브": "ライブ", "오프라인": "オフライン", "채널 상태 필터": "チャンネル状態フィルター", "즉시 스캔": "今すぐスキャン", "전체 중지": "すべて停止",
        "채널 보기 방식": "表示形式", "카드로 보기": "カード表示", "목록으로 보기": "リスト表示", "채널 태그": "チャンネルタグ", "속도": "速度", "비트레이트": "ビットレート",
        "드래그하거나 방향키를 눌러 채널 순서 변경": "ドラッグまたは矢印キーでチャンネルの順序を変更", "채널 제거": "チャンネルを削除", "상태": "状態", "자동 녹화": "自動録画", "다운로드 설정": "ダウンロード設定", "녹화 중단": "録画を停止",
        "저장 경로": "保存先", "저장 위치": "保存場所", "저장 경로 복사": "保存先のパスをコピー", "저장 경로를 복사했습니다.": "保存先のパスをコピーしました。", "저장 경로를 복사하지 못했습니다.": "保存先のパスをコピーできませんでした。", "복사": "コピー", "최근": "最近", "검토": "確認", "X Spaces 다운로드": "X Spacesをダウンロード",
        "녹화 시간": "録画時間", "방송 미리보기": "配信プレビュー", "현재 방송 중이 아닙니다.": "現在配信していません。", "미리보기 크게 보기": "プレビューを拡大", "미리보기를 불러오는 중": "プレビューを読み込み中", "크게 보기": "拡大", "닫기": "閉じる",
        "채팅 로그를 선택해 내용을 확인하세요.": "チャットログを選択して内容を確認してください。", "로그 파일": "ログファイル", "채팅 내용": "チャット内容", "영상 URL": "動画URL",
        "YouTube": "YouTube", "외부 영상": "外部動画", "다시보기 URL 또는 클립 URL": "アーカイブまたはクリップのURL", "핸들(@username) 또는 동영상 ID": "ハンドル（@username）または動画ID", "다운로드할 영상 링크": "ダウンロードする動画のリンク",
        "YouTube 링크, @핸들 또는 11자리 동영상 ID를 입력해 주세요.": "YouTubeのURL、@ハンドル、または11桁の動画IDを入力してください。", "올바른 영상 주소를 입력해 주세요.": "有効な動画URLを入力してください。", "Chzzk 다시보기 또는 클립 주소를 입력해 주세요.": "ChzzkのアーカイブまたはクリップURLを入力してください。",
        "YouTube 링크, @핸들 또는 동영상 ID를 입력해 주세요.": "YouTubeのURL、@ハンドル、または動画IDを入力してください。", "지원되는 외부 영상 주소인지 확인해 주세요.": "対応している動画URLか確認してください。", "다운로드 목록에 추가했습니다.": "ダウンロードキューに追加しました。", "영상 추가에 실패했습니다.": "動画を追加できませんでした。",
        "다운로드 시작": "ダウンロード開始", "다운로드 중지": "ダウンロードを停止", "중지": "停止", "다시 다운로드": "再ダウンロード", "다시 받기": "再試行", "목록 정리": "リストを整理", "정리": "整理",
        "대기·완료·오류 항목을 목록에서 삭제할까요? 진행 중이거나 일시정지한 항목은 유지됩니다.": "待機中・完了・エラーの項目を一覧から削除しますか？進行中または一時停止中の項目は残ります。",
        "서비스 상태 확인": "サービス状態", "실시간 서비스 로그와 일자별 백업을 검색하고 서버 상태를 추적합니다.": "サービスログと日別バックアップを検索し、サーバーの状態を確認します。", "로그 초기화": "ログを消去",
        "X Spaces 주소": "X SpacesのURL", "X Spaces 주소 또는 라이브 대시보드에서 저장한 재생 목록 주소를 붙여넣으세요.": "X SpacesのURL、またはライブダッシュボードで保存したプレイリストのURLを貼り付けてください。", "라이브 대시보드에서 자동 저장한 재생 목록 주소도 사용할 수 있습니다.": "ライブダッシュボードで自動保存したプレイリストのURLも使用できます。",
        "영상 없이 효율적인 오디오 형식으로 저장됩니다.": "動画なしの効率的な音声ファイルとして保存します。", "링크 유효 기간": "リンクの有効期間", "master playlist는 Space 종료 후 약 30일간 유효합니다.": "master playlistはSpace終了後、通常約30日間有効です。", "설정에서 X 쿠키 파일을 먼저 지정해 주세요.": "先に設定でXのCookieファイルを指定してください。", "진행 상황과 저장된 파일은 모니터링의 다시보기 대시보드에서 확인할 수 있습니다.": "進行状況と保存ファイルは、モニタリングの動画ダッシュボードで確認できます。",
        "플랫폼 선택": "プラットフォームを選択", "다운로드 플랫폼": "ダウンロードするプラットフォーム",
        "Before you start": "はじめる前に", "M4A 오디오": "M4A音声", "비공개 Space": "非公開Space",
        "워크스페이스를 준비하고 있습니다": "ワークスペースを準備しています", "Global Command Palette": "グローバルコマンドパレット", "검색하거나 명령어를 입력하세요...": "検索またはコマンドを入力…", "검색 결과가 없습니다.": "検索結果がありません。", "이동 (Navigation)": "移動",
        "일반 설정": "一般設定", "일반 설정이 저장되었습니다.": "一般設定を保存しました。", "일반 설정 저장에 실패했습니다.": "一般設定を保存できませんでした。", "라이브 저장 경로": "ライブ録画の保存先", "라이브 녹화 파일과 해당 방송의 채팅 로그가 저장됩니다.": "ライブ録画と配信のチャットログを保存します。",
        "다시보기 저장 경로": "動画の保存先", "Chzzk 다시보기·클립과 외부 영상 다운로드가 저장됩니다.": "Chzzkのアーカイブ、クリップ、外部動画を保存します。", "감시 주기 (초)": "監視間隔（秒）", "채널 라이브 상태를 확인하는 간격 (5~300초).": "チャンネルの配信状況を確認する間隔（5～300秒）。",
        "라이브 녹화 포맷": "ライブ録画形式", "TS/MKV는 녹화 중단 시에도 파일이 유지됩니다. MP4는 라이브 녹화에 적합하지 않습니다.": "TSとMKVは録画が中断してもファイルを再生できます。MP4はライブ録画に適していません。", "TS — MPEG Transport Stream (권장)": "TS — MPEG Transport Stream（推奨）", "MP4 (권장하지 않음 — 라이브 중단 시 파일 손상 가능)": "MP4（非推奨 — 配信中断時にファイルが破損する可能性があります）", "저장 중...": "保存中…", "일반 설정 저장": "一般設定を保存",
        "디렉토리를 불러올 수 없습니다.": "フォルダーを読み込めませんでした。", "폴더 선택": "フォルダーを選択", "드라이브 목록으로": "ドライブ一覧", "드라이브 선택": "ドライブを選択", "하위 폴더 없음": "サブフォルダーはありません", "취소": "キャンセル", "이 폴더 선택": "このフォルダーを選択", "폴더 찾아보기": "フォルダーを参照", "찾아보기": "参照", "경로 입력...": "パスを入力…",
        "영상 다운로드 설정": "動画ダウンロード設定", "동시 다운로드 개수": "同時ダウンロード数", "한 번에 다운로드할 수 있는 최대 영상 개수 (1~10개)": "一度にダウンロードする動画の最大数（1～10）。", "영상 다운로드 품질": "動画の画質", "영상 다운로드 시 기본으로 사용할 화질": "動画ダウンロードで使用する標準画質。", "최고 화질": "最高画質", "최대 다운로드 속도 (MB/s)": "最大ダウンロード速度（MB/s）", "0 = 무제한, 네트워크 대역폭 제한 시 사용": "0は無制限です。帯域幅を制限する場合に設定してください。",
        "영상 파일 형식": "動画ファイル形式", "MP4 — MPEG-4 (권장)": "MP4 — MPEG-4（推奨）", "다시보기와 클립은 MP4가 여러 기기에서 잘 재생됩니다. 영상과 음성을 합칠 때 ffmpeg를 사용합니다.": "アーカイブやクリップには、多くの端末で再生できるMP4がおすすめです。映像と音声の結合にはffmpegを使用します。", "미완료 영상 파일 보관 (.part)": "未完了の動画ファイルを保持（.part）", "미완료 영상 파일 보관": "未完了の動画ファイルを保持", "취소 또는 오류가 발생해도 미완료 파일을 보관합니다.": "キャンセルやエラー時も未完了ファイルを保持します。", "취소하거나 오류가 발생하면 미완료 파일을 삭제합니다.": "キャンセルまたはエラー時に未完了ファイルを削除します。", "영상 파일명 형식": "動画ファイル名の形式",
        "{name}, {title}, {date_year}, {date_month}, {date_day}, {date_hour}, {date_minute}, {date_second}, {id}, {extractor}, {upload_date}, {download_date}, {quality}를 사용할 수 있습니다. 날짜와 시각은 다운로드 시작 기준이며 확장자는 자동으로 붙습니다.": "使用できる項目: {name}, {title}, {date_year}, {date_month}, {date_day}, {date_hour}, {date_minute}, {date_second}, {id}, {extractor}, {upload_date}, {download_date}, {quality}。日時はダウンロード開始時を基準とし、拡張子は自動で追加されます。", "영상 다운로드 설정 저장": "動画ダウンロード設定を保存", "영상 다운로드 설정을 저장했습니다.": "動画ダウンロード設定を保存しました。", "영상 다운로드 설정 저장에 실패했습니다.": "動画ダウンロード設定を保存できませんでした。",
        "라이브 다운로드 설정": "ライブ録画設定", "라이브 품질": "ライブ画質", "라이브 녹화에 사용할 yt-dlp 화질입니다.": "ライブ録画に使用するyt-dlpの画質です。", "자동 재시도 횟수": "自動再試行回数", "라이브 녹화 중단 시 자동 재시도 횟수.": "ライブ録画が中断したときの自動再試行回数。", "Chzzk 스트림 획득 방법": "Chzzkストリームの取得方法", "타임머신을 강제 사용하며, 사용할 수 없으면 녹화 요청을 실패 처리합니다.": "常にTime Machineを使用します。利用できない場合、録画リクエストは失敗します。", "타임머신 API를 먼저 요청하고, 사용할 수 없으면 기본 스트림으로 자동 전환합니다.": "まずTime Machine APIを呼び出し、利用できない場合は標準ストリームに切り替えます。", "Chzzk 기본 API에서 yt-dlp가 선택한 라이브 스트림을 사용합니다.": "Chzzk標準APIからyt-dlpが選択したライブストリームを使用します。",
        "기본 스트림 사용": "標準ストリームを使用", "가능하면 타임머신 사용": "利用可能な場合Time Machineを使用", "강제로 타임머신 사용": "常にTime Machineを使用", "스트림 시작 오프셋 (초)": "ストリーム開始オフセット（秒）", "타임머신이 제공하는 스트림의 시작점에서 건너뛸 시간입니다. 0이면 사용 가능한 가장 앞부분부터 받습니다.": "Time Machineのストリーム開始位置からスキップする秒数です。0の場合は取得可能な最も古い位置から開始します。", "라이브 미리보기 이미지 저장": "ライブプレビュー画像を保存", "Chzzk 라이브 썸네일을 녹화 파일 옆에 저장합니다.": "Chzzkのサムネイルを録画ファイルと同じ場所に保存します。", "미리보기 이미지를 별도 파일로 저장하지 않습니다.": "プレビュー画像を別ファイルとして保存しません。",
        "라이브 파일명 형식": "ライブ録画ファイル名の形式", "{name}/{channel_name}, {title}/{live_title}, {channel_uid}, {category}, {date_year}, {live_date_year}, {download_date_year}, {live_date_month}, {live_date_day}, {live_date_hour}, {live_date_minute}, {live_date_second}, {quality}, {extension} 사용 가능. 확장자는 자동 추가됩니다.": "使用できる項目: {name}/{channel_name}, {title}/{live_title}, {channel_uid}, {category}, {date_year}, {live_date_year}, {download_date_year}, {live_date_month}, {live_date_day}, {live_date_hour}, {live_date_minute}, {live_date_second}, {quality}, {extension}。拡張子は自動で追加されます。", "라이브 설정 저장": "ライブ設定を保存", "라이브 설정이 저장되었습니다.": "ライブ設定を保存しました。", "라이브 설정 저장에 실패했습니다.": "ライブ設定を保存できませんでした。", "실시간 채팅 설정": "ライブチャット設定", "라이브 채팅 저장": "ライブチャットを保存", "녹화 중 채팅을 JSONL 파일로 자동 저장합니다.": "録画中のチャットをJSONLファイルに自動保存します。", "라이브 채팅을 저장하지 않습니다.": "ライブチャットを保存しません。", "채팅 설정 저장": "チャット設定を保存", "채팅 설정이 저장되었습니다.": "チャット設定を保存しました。", "채팅 설정 저장에 실패했습니다.": "チャット設定を保存できませんでした。",
    },
};

interface LanguageContextValue {
    language: Language;
    setLanguage: (language: Language) => void;
    t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);
const STORAGE_KEY = "phrolova-language";

function readLanguage(): Language {
    try {
        const value = localStorage.getItem(STORAGE_KEY);
        return value === "en" || value === "ja" || value === "ko" ? value : "ko";
    } catch {
        return "ko";
    }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>(readLanguage);

    const setLanguage = (next: Language) => {
        setLanguageState(next);
        try { localStorage.setItem(STORAGE_KEY, next); } catch { /* Preferences may be unavailable in private mode. */ }
    };

    useEffect(() => {
        document.documentElement.lang = language;
    }, [language]);

    const value = useMemo<LanguageContextValue>(() => ({
        language,
        setLanguage,
        t: (text) => language === "ko" ? text : messages[language][text] ?? text,
    }), [language]);

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
    const value = useContext(LanguageContext);
    if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
    return value;
}
